-- GRUOP BY: 여러 데이터에서 의미있는 하나의 결과를 특정 열 값별로 묶어서 출력할때 사용
SELECT ROUND(AVG(SAL,2)) AS 사원전체평균
FROM EMP;

-- 부서별 사원 평균
SELECT DEPTNO, ROUND(AVG(SAL),2) AS 부서별평균
FROM EMP
GROUP BY DEPTNO
DORDER BY DEPTNO;

--GROUP BY 절 없이 구현한다면?
SELECT AVG(SAL)FROM EMP WHERE DEPTNO = 10;
SELECT AVG(SAL)FROM EMP WHERE DEPTNO = 20;
SELECT AVG(SAL)FROM EMP WHERE DEPTNO = 30;

--집합연산자를 사용하여 구현하기
SELECT AVG(SAL)FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT AVG(SAL)FROM EMP WHERE DEPTNO = 20
UNION ALL
SELECT AVG(SAL)FROM EMP WHERE DEPTNO = 30;

--부서코드, 급여합계, 부서평균 AS 생략 가능
SELECT DEPTNO 부서코드, 
    SUM(SAL) 합계,
    ROUND(AVG(SAL),2) 평균,
    COUNT(*) 인원수
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

--HAVING절 : GROUP BY 절이 존재하는 경우에만 사용 가능
--GROUP BY 절을 통해 그룹화된 결과 값의 범위를 제한할 때 사용